"""
BREAKPOINT — Playwright Test Generator
Turns a ConfirmedBug + recorded actions into a runnable .spec.js file.
This is the WOW moment: the agent hands you a test that proves the bug.
"""

from __future__ import annotations

import logging
import os
from typing import Any

from backend.agent.llm import llm_call_json
from backend.agent.prompts import build_playwright_test_prompt
from backend.schemas.models import AgentAction, ActionType, ConfirmedBug

log = logging.getLogger("breakpoint.testgen")


# ---------------------------------------------------------------------------
# Main generator
# ---------------------------------------------------------------------------

async def generate_playwright_test(
    bug: ConfirmedBug,
    recorded_actions: list[AgentAction],
    base_url: str = "http://localhost:3000",
    output_dir: str = ".",
) -> str | None:
    """
    Generate a Playwright test file for a confirmed bug.
    Returns the file path if successful, None otherwise.
    """
    log.info("[TESTGEN] Generating Playwright test for bug: %s", bug.id)

    # Try LLM generation first
    actions_dicts = [
        {
            "action": a.action,
            "url": a.url,
            "selector": a.selector,
            "text": a.text,
            "reason": a.reason,
        }
        for a in recorded_actions
        if a.action not in (ActionType.FINISH,)
    ]

    bug_dict = bug.to_summary()
    prompt = build_playwright_test_prompt(bug_dict, actions_dicts, base_url)

    raw = await llm_call_json(
        system_prompt="You are a Playwright test generator. Return only valid JSON with the test code.",
        user_prompt=prompt,
        temperature=0.1,
        max_tokens=1200,
    )

    if raw and raw.get("test_code"):
        filename = raw.get("filename", f"bug_{bug.id.lower()}.spec.js")
        test_code = raw["test_code"].replace("\\n", "\n")
        path = _write_test(filename, test_code, output_dir)
        log.info("[TESTGEN] Generated: %s", path)
        return path

    # LLM failed — generate deterministically
    log.warning("[TESTGEN] LLM failed. Using deterministic test generator.")
    return _generate_deterministic(bug, recorded_actions, base_url, output_dir)


# ---------------------------------------------------------------------------
# Deterministic fallback generator
# ---------------------------------------------------------------------------

def _generate_deterministic(
    bug: ConfirmedBug,
    recorded_actions: list[AgentAction],
    base_url: str,
    output_dir: str,
) -> str:
    """Generate a Playwright test directly from recorded actions. No LLM needed."""

    lines = [
        f"// GENERATED BY BREAKPOINT — {bug.id}",
        f"// Bug: {bug.title}",
        f"// Confidence: {bug.confidence} | Severity: {bug.severity}",
        f"// Reproduced: {bug.reproduction_successes}/{bug.reproduction_attempts}",
        "//",
        f"// Expected: {bug.expected_behavior}",
        f"// Actual:   {bug.actual_behavior}",
        "",
        "const { test, expect } = require('@playwright/test');",
        "",
        f"test('{bug.title}', async ({{ page }}) => {{",
        f"  // This test SHOULD FAIL — it proves the bug exists.",
        f"  // When the bug is fixed, the assertion will pass.",
        "",
    ]

    # Convert recorded actions to Playwright code
    for action in recorded_actions:
        if action.action == ActionType.NAVIGATE and action.url:
            lines.append(f"  await page.goto('{action.url}');  // {action.reason}")
        elif action.action == ActionType.CLICK and action.selector:
            lines.append(f"  await page.click('{action.selector}');  // {action.reason}")
        elif action.action == ActionType.TYPE and action.selector and action.text:
            lines.append(f"  await page.fill('{action.selector}', '{action.text}');  // {action.reason}")
        elif action.action == ActionType.BACK:
            lines.append(f"  await page.goBack();  // {action.reason}")
        elif action.action == ActionType.FORWARD:
            lines.append(f"  await page.goForward();  // {action.reason}")
        elif action.action == ActionType.REFRESH:
            lines.append(f"  await page.reload();  // {action.reason}")
        elif action.action == ActionType.OBSERVE:
            lines.append(f"  // [observe] {action.reason}")

    lines += [
        "",
        "  // ── ASSERTION: This is where the bug manifests ──",
        "  //",
        f"  // Expected: {bug.expected_behavior}",
        f"  // Actual (bug): {bug.actual_behavior}",
        "  //",
    ]

    # Generate assertions based on bug evidence
    if bug.evidence:
        lines.append("  // Evidence captured during investigation:")
        for e in bug.evidence[:3]:
            lines.append(f"  //   {e[:100]}")
        lines.append("")

    # Generic assertion that forces the test to show the bug
    lines += [
        "  // The assertion below will FAIL because the bug is present.",
        "  // Replace with the specific selector and expected value for your app:",
        "  const pageContent = await page.content();",
        f"  // BREAKPOINT detected: {bug.actual_behavior}",
        "  // Uncomment and adapt for your specific selectors:",
        "  // const actualValue = await page.textContent('[data-testid=\"checkout-total\"]');",
        "  // const cartValue   = await page.textContent('[data-testid=\"cart-total\"]');",
        "  // expect(actualValue).toBe(cartValue);  // FAILS — bug confirmed",
        "});",
        "",
        "// Reproduction steps:",
    ]
    for i, step in enumerate(bug.reproduction_steps, 1):
        lines.append(f"// {i}. {step}")

    test_code = "\n".join(lines)
    filename = f"bug_{bug.id.lower().replace('-', '_')}.spec.js"
    return _write_test(filename, test_code, output_dir)


# ---------------------------------------------------------------------------
# File writing
# ---------------------------------------------------------------------------

def _write_test(filename: str, code: str, output_dir: str) -> str:
    os.makedirs(output_dir, exist_ok=True)
    path = os.path.join(output_dir, filename)
    with open(path, "w") as f:
        f.write(code)
    return path
